[tool.poetry]
name = "generalization"
version = "0.1.0"
description = ""
authors = ["Ethan Brooks <ethanabrooks@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
stable-baselines3 = "^1.4.0"
gym-miniworld = {git = "https://github.com/GPT-RL/gym-miniworld.git"}
sweep-logger = {git = "https://github.com/run-tracker/sweep-logger.git", rev = "main"}
transformers = "^4.16.2"
typed-argument-parser = "^1.7.2"
ansicolors = "^1.1.8"
art = "^5.4"

[tool.poetry.dev-dependencies]
ipdb = "^0.13.9"
ipython = "^7.28.0"
black = "^21.9b0"
pre-commit = "^2.16.0"
pymeshlab = "^2021.10"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
